name: Deploy
on:
  pull_request:

permissions:
  contents: read
  pages: write
  id-token: write
  deployments: write
  statuses: write
  checks: write

jobs:
  deploy-preview:
    # if the source repository for pull request is a fork, we don't want to run this workflow,
    # we run deploy_preview_forks.yml which uses pull_request_target instead.
    # see https://github.com/primer/react/pull/2207 for details
    if: ${{ github.event.pull_request.head.repo.full_name == 'primer/react' }} # source repository for pull_request
    name: Preview
    uses: primer/.github/.github/workflows/deploy_preview.yml@0cec9b9914f358846163f2428663b58da41028c9
    permissions:
      contents: read
      pages: write
      id-token: write
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
    with:
      node_version: 16
      install: npm ci && cd docs && npm ci --legacy-peer-deps && cd ..
      build: npm run build:docs:preview
      output_dir: docs/public

  deploy-storybook:
    if: ${{ github.repository == 'primer/react' }}
    name: Preview Storybook
    runs-on: ubuntu-latest
    needs: deploy-preview
    steps:
      - uses: chrnorm/deployment-action@v2.0.5
        name: Create GitHub deployment for storybook
        id: storybook
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: storybook-preview-${{ github.event.number }}
          environment_url: '${{ needs.deploy-preview.outputs.deployment_url }}/storybook'
      - name: Update storybook deployment status (success)
        if: success()
        uses: chrnorm/deployment-status@v2.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment-url: '${{ needs.deploy-preview.outputs.deployment_url }}/storybook'
          state: 'success'
          deployment-id: ${{ steps.storybook.outputs.deployment_id }}
      - name: Update storybook deployment status (failure)
        if: failure()
        uses: chrnorm/deployment-status@v2.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          state: 'failure'
          deployment-id: ${{ steps.storybook.outputs.deployment_id }}
