name: Deploy Preview
on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  storybook:
    name: Pre-Build Storybook
    if: ${{ github.event.pull_request.head.repo.full_name == 'primer/react' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Set up Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version: 22
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build and Cache storybook
        uses: ./.github/actions/storybook

  vrt-reports:
    if: ${{ github.event.pull_request.head.repo.full_name == 'primer/react' }}
    needs: storybook
    uses: ./.github/workflows/vrt-reports.yml

  aat-reports:
    if: ${{ github.event.pull_request.head.repo.full_name == 'primer/react' }}
    needs: storybook
    uses: ./.github/workflows/aat-reports.yml

  build:
    if: ${{ always() && github.event.pull_request.head.repo.full_name == 'primer/react' }}
    needs: [vrt-reports, aat-reports]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Set up Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version: 22
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build docs preview
        run: npm run build:docs:preview
      - name: Download VRT reports
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093
        with:
          name: vrt
          path: docs/public/vrt
      - name: Download AAT reports
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093
        with:
          name: aat
          path: docs/public/aat
      - uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa
        with:
          name: github-pages
          path: docs/public

  deploy-preview:
    if: ${{ always() && github.event.pull_request.head.repo.full_name == 'primer/react' }}
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    outputs:
      deployment_url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e
        with:
          preview: true

  deploy-storybook:
    name: Preview Storybook
    if: ${{ always() && github.event.pull_request.head.repo.full_name == 'primer/react' }}
    needs: deploy-preview
    permissions:
      deployments: write
    runs-on: ubuntu-latest
    steps:
      - uses: chrnorm/deployment-action@55729fcebec3d284f60f5bcabbd8376437d696b1
        name: Create GitHub deployment for storybook
        id: storybook
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: storybook-preview-${{ github.event.number }}
          environment-url: '${{ needs.deploy-preview.outputs.deployment_url }}storybook'
      - name: Update storybook deployment status (success)
        if: success()
        uses: chrnorm/deployment-status@9a72af4586197112e0491ea843682b5dc280d806
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment-url: '${{ needs.deploy-preview.outputs.deployment_url }}storybook'
          state: 'success'
          deployment-id: ${{ steps.storybook.outputs.deployment_id }}
      - name: Update storybook deployment status (failure)
        if: failure()
        uses: chrnorm/deployment-status@9a72af4586197112e0491ea843682b5dc280d806
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          state: 'failure'
          deployment-id: ${{ steps.storybook.outputs.deployment_id }}
