name: Deploy Preview (with VRT/AAT reports)
on:
  workflow_run:
    workflows: [CI]
    types:
      - completed

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    if: ${{ always() && github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.head_repository.full_name == 'primer/react' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build docs preview
        run: npm run build:docs:preview_with_reports
      - name: Download VRT reports (All flags enabled)
        uses: actions/download-artifact@v4
        with:
          name: vrt-all-flags
          path: docs/public/vrt-all-flags
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.event.workflow_run.head_repository.full_name }}
          run-id: ${{ github.event.workflow_run.id }}
      - name: Download VRT reports (No flags enabled)
        uses: actions/download-artifact@v4
        with:
          name: vrt-no-flag
          path: docs/public/vrt-no-flag
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.event.workflow_run.head_repository.full_name }}
          run-id: ${{ github.event.workflow_run.id }}
      - name: Download AAT reports (All flags enabled)
        uses: actions/download-artifact@v4
        with:
          name: axe-all-flags
          path: docs/public/aat-all-flags
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.event.workflow_run.head_repository.full_name }}
          run-id: ${{ github.event.workflow_run.id }}
      - name: Download AAT reports (No flags enabled)
        uses: actions/download-artifact@v4
        with:
          name: axe
          path: docs/public/aat-no-flag
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.event.workflow_run.head_repository.full_name }}
          run-id: ${{ github.event.workflow_run.id }}
      - uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: docs/public

  deploy-preview:
    if: ${{ github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.head_repository.full_name == 'primer/react' }}
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    outputs:
      deployment_url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          preview: true

  deploy-storybook:
    name: Preview Storybook
    if: ${{ github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.head_repository.full_name == 'primer/react' }}
    needs: deploy-preview
    permissions:
      deployments: write
    runs-on: ubuntu-latest
    steps:
      - uses: chrnorm/deployment-action@v2.0.7
        name: Create GitHub deployment for storybook
        id: storybook
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: storybook-preview-${{ github.event.workflow_run.event.number }}
          environment-url: '${{ needs.deploy-preview.outputs.deployment_url }}storybook'
      - name: Update storybook deployment status (success)
        if: success()
        uses: chrnorm/deployment-status@v2.0.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment-url: '${{ needs.deploy-preview.outputs.deployment_url }}storybook'
          state: 'success'
          deployment-id: ${{ steps.storybook.outputs.deployment_id }}
      - name: Update storybook deployment status (failure)
        if: failure()
        uses: chrnorm/deployment-status@v2.0.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          state: 'failure'
          deployment-id: ${{ steps.storybook.outputs.deployment_id }}

  deploy-vrt-no-flag:
    name: VRT (No flags enabled)
    if: ${{ github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.head_repository.full_name == 'primer/react' }}
    needs: [deploy-preview]
    permissions:
      deployments: write
    runs-on: ubuntu-latest
    steps:
      - uses: chrnorm/deployment-action@v2.0.7
        name: Create GitHub deployment for vrt-no-flag
        id: vrt-no-flag
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: vrt-no-flag-${{ github.event.workflow_run.head_branch }}
          environment-url: '${{ needs.deploy-preview.outputs.deployment_url }}vrt-no-flag'
      - name: Update vrt-no-flag deployment status (success)
        if: success()
        uses: chrnorm/deployment-status@v2.0.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment-url: '${{ needs.deploy-preview.outputs.deployment_url }}vrt-no-flag'
          state: 'success'
          deployment-id: ${{ steps.vrt-no-flag.outputs.deployment_id }}
      - name: Update vrt-no-flag deployment status (failure)
        if: failure()
        uses: chrnorm/deployment-status@v2.0.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          state: 'failure'
          deployment-id: ${{ steps.vrt-no-flag.outputs.deployment_id }}

  deploy-vrt-all-flags:
    name: VRT (All flags enabled)
    if: ${{ github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.head_repository.full_name == 'primer/react' }}
    needs: deploy-preview
    permissions:
      deployments: write
    runs-on: ubuntu-latest
    steps:
      - uses: chrnorm/deployment-action@v2.0.7
        name: Create GitHub deployment for vrt-all-flags
        id: vrt-all-flags
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: vrt-all-flags-${{ github.event.workflow_run.event.number }}
          environment-url: '${{ needs.deploy-preview.outputs.deployment_url }}vrt-all-flags'
      - name: Update vrt-all-flags deployment status (success)
        if: success()
        uses: chrnorm/deployment-status@v2.0.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment-url: '${{ needs.deploy-preview.outputs.deployment_url }}vrt-all-flags'
          state: 'success'
          deployment-id: ${{ steps.vrt-all-flags.outputs.deployment_id }}
      - name: Update vrt-all-flags deployment status (failure)
        if: failure()
        uses: chrnorm/deployment-status@v2.0.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          state: 'failure'
          deployment-id: ${{ steps.vrt-all-flags.outputs.deployment_id }}

  deploy-aat-no-flag:
    name: AAT (No flags enabled)
    if: ${{ github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.head_repository.full_name == 'primer/react' }}
    needs: deploy-preview
    permissions:
      deployments: write
    runs-on: ubuntu-latest
    steps:
      - uses: chrnorm/deployment-action@v2.0.7
        name: Create GitHub deployment for aat-no-flag
        id: aat-no-flag
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: aat-no-flag-${{ github.event.workflow_run.event.number }}
          environment-url: '${{ needs.deploy-preview.outputs.deployment_url }}aat-no-flag'
      - name: Update aat-no-flag deployment status (success)
        if: success()
        uses: chrnorm/deployment-status@v2.0.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment-url: '${{ needs.deploy-preview.outputs.deployment_url }}aat-no-flag'
          state: 'success'
          deployment-id: ${{ steps.aat-no-flag.outputs.deployment_id }}
      - name: Update aat-no-flag deployment status (failure)
        if: failure()
        uses: chrnorm/deployment-status@v2.0.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          state: 'failure'
          deployment-id: ${{ steps.aat-no-flag.outputs.deployment_id }}

  deploy-aat-all-flags:
    name: AAT (All flags enabled)
    if: ${{ github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.head_repository.full_name == 'primer/react' }}
    needs: deploy-preview
    permissions:
      deployments: write
    runs-on: ubuntu-latest
    steps:
      - uses: chrnorm/deployment-action@v2.0.7
        name: Create GitHub deployment for aat-all-flags
        id: aat-all-flags
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: aat-all-flags-${{ github.event.workflow_run.event.number }}
          environment-url: '${{ needs.deploy-preview.outputs.deployment_url }}aat-all-flags'
      - name: Update aat-all-flags deployment status (success)
        if: success()
        uses: chrnorm/deployment-status@v2.0.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment-url: '${{ needs.deploy-preview.outputs.deployment_url }}aat-all-flags'
          state: 'success'
          deployment-id: ${{ steps.aat-all-flags.outputs.deployment_id }}
      - name: Update aat-all-flags deployment status (failure)
        if: failure()
        uses: chrnorm/deployment-status@v2.0.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          state: 'failure'
          deployment-id: ${{ steps.aat-all-flags.outputs.deployment_id }}
