name: Deploy (fork)
on:
  pull_request_target:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy-preview:
    # target repository for pull_request is primer/react but source repository isn't primer/react
    if: ${{ github.repository == 'primer/react' && github.event.pull_request.head.repo.full_name != 'primer/react' }}
    name: Preview
    uses: primer/.github/.github/workflows/deploy_preview.yml@0cec9b9914f358846163f2428663b58da41028c9
    permissions:
      contents: read
      pages: write
      id-token: write
    with:
      node_version: 16
      install: npm ci && cd docs && npm ci && cd ..
      build: npm run build:docs:preview
      output_dir: docs/public
