name: Update status project

on:
  push:
    branches:
      - main
    # Only run workflow on changes to component docs
    paths:
      - 'docs/content/**'

jobs:
  build-and-deploy:
    name: Update status project
    if: ${{ github.repository == 'primer/react' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Set up Node.js
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f
        with:
          node-version-file: '.nvmrc'
      - name: Install node deps
        run: npm ci
      - name: Install ruby deps
        run: gem install graphql-client
      - name: Build statuses
        run: npx ts-node script/component-status-project/build.ts
      - name: Deploy statuses to project
        run: GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} script/component-status-project/deploy.rb
